import Head from "next/head"
import styles from "../styles/Home.module.css"
//import ManualHeader from "../components/ManualHeader"
import Header from "../components/Header"
import LotteryEntrance from "../components/LotteryEntrance"
import React from "react"

const supportedChains = ["31337", "4"]

export default function Home() {
    return (
        <main>
            <div class="bg-neutral-200 pt-10 pb-8 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-3xl sm:rounded-lg sm:px-10">
                <Head>
                    <title>Decentralised Lottery</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <React.StrictMode>
                    <LotteryEntrance />
                </React.StrictMode>
            </div>
        </main>
    )
}
